# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uhlm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uhlm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuhlm.proto\x12\x04uhlm\"\x1a\n\x08\x42\x65ginReq\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"1\n\tBeginResp\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\r\"\x16\n\x05\x44\x65nse\x12\r\n\x05probs\x18\x01 \x03(\x02\",\n\nSparseTopK\x12\x0f\n\x07indices\x18\x01 \x03(\r\x12\r\n\x05probs\x18\x02 \x03(\x02\"\x80\x01\n\tVerifyReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x64raft_id\x18\x02 \x01(\r\x12\x1c\n\x05\x64\x65nse\x18\x03 \x01(\x0b\x32\x0b.uhlm.DenseH\x00\x12\"\n\x06sparse\x18\x04 \x01(\x0b\x32\x10.uhlm.SparseTopKH\x00\x42\x0b\n\tslm_probs\"D\n\nVerifyResp\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x10\n\x08token_id\x18\x02 \x01(\r\x12\x12\n\nnew_length\x18\x03 \x01(\r\"/\n\x07SyncReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08tail_ids\x18\x02 \x03(\r\"\x1e\n\x08SyncResp\x12\x12\n\nnew_length\x18\x01 \x01(\r\"\x1c\n\x06\x45ndReq\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\x1a\n\x07\x45ndResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbb\x01\n\x04UHLM\x12/\n\x0c\x42\x65ginSession\x12\x0e.uhlm.BeginReq\x1a\x0f.uhlm.BeginResp\x12\x30\n\x0bVerifyToken\x12\x0f.uhlm.VerifyReq\x1a\x10.uhlm.VerifyResp\x12%\n\x04Sync\x12\r.uhlm.SyncReq\x1a\x0e.uhlm.SyncResp\x12)\n\nEndSession\x12\x0c.uhlm.EndReq\x1a\r.uhlm.EndRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uhlm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BEGINREQ']._serialized_start=20
  _globals['_BEGINREQ']._serialized_end=46
  _globals['_BEGINRESP']._serialized_start=48
  _globals['_BEGINRESP']._serialized_end=97
  _globals['_DENSE']._serialized_start=99
  _globals['_DENSE']._serialized_end=121
  _globals['_SPARSETOPK']._serialized_start=123
  _globals['_SPARSETOPK']._serialized_end=167
  _globals['_VERIFYREQ']._serialized_start=170
  _globals['_VERIFYREQ']._serialized_end=298
  _globals['_VERIFYRESP']._serialized_start=300
  _globals['_VERIFYRESP']._serialized_end=368
  _globals['_SYNCREQ']._serialized_start=370
  _globals['_SYNCREQ']._serialized_end=417
  _globals['_SYNCRESP']._serialized_start=419
  _globals['_SYNCRESP']._serialized_end=449
  _globals['_ENDREQ']._serialized_start=451
  _globals['_ENDREQ']._serialized_end=479
  _globals['_ENDRESP']._serialized_start=481
  _globals['_ENDRESP']._serialized_end=507
  _globals['_UHLM']._serialized_start=510
  _globals['_UHLM']._serialized_end=697
# @@protoc_insertion_point(module_scope)
