# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# import uhlm_pb2 as uhlm__pb2
from . import uhlm_pb2 as uhlm__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uhlm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UHLMStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginSession = channel.unary_unary(
                '/uhlm.UHLM/BeginSession',
                request_serializer=uhlm__pb2.BeginReq.SerializeToString,
                response_deserializer=uhlm__pb2.BeginResp.FromString,
                _registered_method=True)
        self.VerifyToken = channel.unary_unary(
                '/uhlm.UHLM/VerifyToken',
                request_serializer=uhlm__pb2.VerifyReq.SerializeToString,
                response_deserializer=uhlm__pb2.VerifyResp.FromString,
                _registered_method=True)
        self.Sync = channel.unary_unary(
                '/uhlm.UHLM/Sync',
                request_serializer=uhlm__pb2.SyncReq.SerializeToString,
                response_deserializer=uhlm__pb2.SyncResp.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/uhlm.UHLM/EndSession',
                request_serializer=uhlm__pb2.EndReq.SerializeToString,
                response_deserializer=uhlm__pb2.EndResp.FromString,
                _registered_method=True)


class UHLMServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BeginSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UHLMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginSession': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginSession,
                    request_deserializer=uhlm__pb2.BeginReq.FromString,
                    response_serializer=uhlm__pb2.BeginResp.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=uhlm__pb2.VerifyReq.FromString,
                    response_serializer=uhlm__pb2.VerifyResp.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=uhlm__pb2.SyncReq.FromString,
                    response_serializer=uhlm__pb2.SyncResp.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=uhlm__pb2.EndReq.FromString,
                    response_serializer=uhlm__pb2.EndResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uhlm.UHLM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uhlm.UHLM', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UHLM(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BeginSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uhlm.UHLM/BeginSession',
            uhlm__pb2.BeginReq.SerializeToString,
            uhlm__pb2.BeginResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uhlm.UHLM/VerifyToken',
            uhlm__pb2.VerifyReq.SerializeToString,
            uhlm__pb2.VerifyResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uhlm.UHLM/Sync',
            uhlm__pb2.SyncReq.SerializeToString,
            uhlm__pb2.SyncResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uhlm.UHLM/EndSession',
            uhlm__pb2.EndReq.SerializeToString,
            uhlm__pb2.EndResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
