# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import verifier_pb2 as verifier__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in verifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMVerifierStub(object):
    """Service defining the methods for the LLM verification process.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyTokens = channel.unary_unary(
                '/LLMVerifier/VerifyTokens',
                request_serializer=verifier__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verifier__pb2.VerificationResponse.FromString,
                _registered_method=True)


class LLMVerifierServicer(object):
    """Service defining the methods for the LLM verification process.
    """

    def VerifyTokens(self, request, context):
        """Unary RPC method for checking a batch of speculative tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMVerifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTokens,
                    request_deserializer=verifier__pb2.VerificationRequest.FromString,
                    response_serializer=verifier__pb2.VerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LLMVerifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('LLMVerifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMVerifier(object):
    """Service defining the methods for the LLM verification process.
    """

    @staticmethod
    def VerifyTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/LLMVerifier/VerifyTokens',
            verifier__pb2.VerificationRequest.SerializeToString,
            verifier__pb2.VerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
