# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: verifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'verifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0everifier.proto\"b\n\x13VerificationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\x12\x12\n\nvocab_size\x18\x04 \x01(\x05\"Z\n\x14VerificationResponse\x12\x12\n\nfinal_text\x18\x01 \x01(\t\x12\x12\n\nraw_logits\x18\x02 \x01(\x0c\x12\x1a\n\x12verified_token_ids\x18\x03 \x03(\x05\x32J\n\x0bLLMVerifier\x12;\n\x0cVerifyTokens\x12\x14.VerificationRequest\x1a\x15.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'verifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=18
  _globals['_VERIFICATIONREQUEST']._serialized_end=116
  _globals['_VERIFICATIONRESPONSE']._serialized_start=118
  _globals['_VERIFICATIONRESPONSE']._serialized_end=208
  _globals['_LLMVERIFIER']._serialized_start=210
  _globals['_LLMVERIFIER']._serialized_end=284
# @@protoc_insertion_point(module_scope)
